import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ButtonLink, Container, SectionHeading } from "@/components/ui";
import { PageHero } from "@/components/content";

const services = {
  "modernizacao-de-sistemas": {
    title: "Modernização de sistemas legados", intro: "Evolua aplicações essenciais sem transformar uma mudança técnica em risco operacional.", description: "Mapeamos dependências, isolamos componentes e definimos uma sequência de migração compatível com a realidade do seu sistema, da equipe e da operação.", benefits: ["Redução de risco em mudanças críticas", "Preservação de regras de negócio", "Roadmap incremental e mensurável"], technologies: ["ASP Classic", ".NET", "C#", "VB6", "SQL Server", "Oracle"], uses: ["ERPs e aplicações internas", "Portais corporativos", "Sistemas web de missão crítica"], process: ["Inventário técnico", "Mapa de dependências", "Priorização por risco", "Execução incremental"]
  },
  "desenvolvimento-sob-medida": {
    title: "Desenvolvimento sob medida", intro: "Construa sistemas para as regras do seu negócio, sem adaptar a operação a limitações de uma solução pronta.", description: "Projetamos e desenvolvemos aplicações internas, portais, backoffices e produtos SaaS com arquitetura clara, segurança e espaço para evolução.", benefits: ["Aderência aos processos reais", "Arquitetura preparada para crescimento", "Visibilidade sobre custo e evolução"], technologies: [".NET", "PHP", "Python", "React", "Next.js", "TypeScript", "PostgreSQL"], uses: ["Backoffices operacionais", "Portais para clientes e parceiros", "Produtos SaaS B2B"], process: ["Descoberta e escopo", "Arquitetura da solução", "Desenvolvimento incremental", "Entrega e evolução"]
  },
  "sustentacao-e-evolucao": {
    title: "Sustentação e evolução", intro: "Mantenha aplicações corporativas confiáveis enquanto a próxima evolução é planejada.", description: "Atuamos sobre incidentes, correções, documentação e melhorias com prioridade orientada ao impacto na operação e registro das decisões.", benefits: ["Menor tempo para diagnóstico de incidentes", "Continuidade do conhecimento técnico", "Evolução sem acumular correções improvisadas"], technologies: [".NET", "PHP", "SQL Server", "Oracle", "IIS", "Logs e monitoramento"], uses: ["Aplicações em produção", "Sistemas sem documentação atualizada", "Operações dependentes de conhecimento concentrado"], process: ["Entendimento do ambiente", "Classificação de prioridades", "Correção e validação", "Documentação e evolução"]
  },
  "integracoes-e-apis": {
    title: "Integrações e APIs", intro: "Conecte ERPs, aplicações e serviços externos com contratos claros e rastreabilidade de ponta a ponta.", description: "Desenhamos integrações considerando autenticação, idempotência, falhas esperadas, reprocessamento, logs e documentação para reduzir intervenção manual.", benefits: ["Menos processos manuais e retrabalho", "Falhas rastreáveis e reprocessáveis", "Contratos que sustentam a evolução"], technologies: ["REST", "SOAP", "JSON", "XML", "OpenAPI", "OAuth", "SQL Server"], uses: ["Integrações com ERP", "Sincronização de dados", "APIs para parceiros e canais"], process: ["Mapeamento de contratos", "Desenho de fluxos", "Implementação e testes", "Monitoramento e operação"]
  },
  "dados-e-bi": {
    title: "Dados e BI", intro: "Transforme dados dispersos em indicadores consistentes para decisões operacionais e executivas.", description: "Estruturamos fontes, modelos, consultas e indicadores antes de construir painéis. O resultado é uma camada de informação que pode ser auditada e mantida.", benefits: ["Indicadores com definição única", "Menor dependência de planilhas manuais", "Análises mais rápidas e confiáveis"], technologies: ["Power BI", "DAX", "Power Query", "Oracle", "SQL Server", "Modelagem dimensional"], uses: ["Dashboards executivos", "Indicadores operacionais", "Análise financeira e de performance"], process: ["Inventário das fontes", "Modelagem dos dados", "Validação dos indicadores", "Publicação e governança"]
  },
  "ia-e-automacao": {
    title: "IA e automação", intro: "Aplique inteligência artificial e automação em processos onde velocidade, padronização e validação fazem diferença.", description: "Definimos limites de uso, dados permitidos, critérios de validação e integração com a operação para que a tecnologia seja controlável e útil.", benefits: ["Redução de tarefas repetitivas", "Padronização de análises e documentos", "Apoio à decisão com supervisão humana"], technologies: ["Python", "APIs de modelos", "OCR", "Classificação", "Automação de processos", "Integrações"], uses: ["Extração e classificação de documentos", "Assistentes internos", "Automação de rotinas administrativas"], process: ["Seleção do caso de uso", "Prova de valor controlada", "Validação humana", "Integração e acompanhamento"]
  }
} as const;

type Slug = keyof typeof services;
export function generateStaticParams() { return Object.keys(services).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const service = services[slug as Slug]; return service ? { title: service.title, description: service.intro } : {}; }

export default async function ServicePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const service = services[slug as Slug]; if (!service) notFound();
  return <>
    <PageHero eyebrow="Serviços" title={service.title} text={service.intro} />
    <section className="py-16 sm:py-24"><Container className="grid gap-12 lg:grid-cols-[1.15fr_.85fr] lg:items-start"><SectionHeading eyebrow="Descrição" title="Uma solução técnica conectada à operação" text={service.description} /><div className="card border-t-4 border-t-blue-600"><h3 className="font-semibold text-slate-900">Onde entregamos valor</h3><ul className="mt-5 grid gap-3 text-sm leading-6 text-slate-600">{service.benefits.map((item) => <li key={item}>✓ {item}</li>)}</ul></div></Container></section>
    <section className="bg-slate-50 py-16 sm:py-24"><Container><SectionHeading eyebrow="Benefícios" title="Impacto técnico que aparece no negócio" /><div className="mt-10 grid gap-5 md:grid-cols-3">{service.benefits.map((item, index) => <article className="card" key={item}><span className="text-sm font-bold text-blue-700">0{index + 1}</span><h3 className="mt-5 font-semibold text-slate-900">{item}</h3><p className="mt-3 text-sm leading-6 text-slate-600">Resultado orientado a continuidade, clareza e capacidade de evolução.</p></article>)}</div></Container></section>
    <section className="py-16 sm:py-24"><Container className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><SectionHeading eyebrow="Tecnologias" title="A stack acompanha o contexto" text="Selecionamos ferramentas compatíveis com os sistemas existentes, os requisitos de segurança e a capacidade de manutenção da equipe." /></div><div className="flex flex-wrap content-start gap-2">{service.technologies.map((technology) => <span className="rounded border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-700" key={technology}>{technology}</span>)}</div></Container></section>
    <section className="bg-slate-950 py-16 text-white sm:py-24"><Container><SectionHeading eyebrow="Processo" title="Trabalho organizado em etapas verificáveis" text="Cada fase produz evidências para a próxima decisão, reduzindo retrabalho e tornando o avanço mensurável." /><ol className="mt-10 grid gap-4 md:grid-cols-4">{service.process.map((item, index) => <li className="border border-slate-700 bg-slate-900/70 p-5" key={item}><span className="text-sm font-bold text-blue-400">0{index + 1}</span><h3 className="mt-5 font-semibold">{item}</h3><p className="mt-3 text-sm leading-6 text-slate-300">Escopo claro, validação com as pessoas envolvidas e registro das decisões técnicas.</p></li>)}</ol></Container></section>
    <section className="py-16 sm:py-24"><Container><SectionHeading eyebrow="Casos de uso" title="Onde este serviço costuma ser decisivo" /><div className="mt-10 grid gap-4 md:grid-cols-3">{service.uses.map((item) => <div className="card" key={item}><h3 className="font-semibold text-slate-900">{item}</h3><p className="mt-3 text-sm leading-6 text-slate-600">Cenários em que confiabilidade, integração e evolução técnica precisam caminhar juntas.</p></div>)}</div></Container></section>
    <section className="bg-blue-700 py-16 text-white sm:py-20"><Container className="flex flex-col gap-7 md:flex-row md:items-center md:justify-between"><div><p className="eyebrow text-blue-200">Próximo passo</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold tracking-tight sm:text-4xl">Vamos avaliar o contexto técnico da sua operação?</h2><p className="mt-4 max-w-2xl leading-7 text-blue-100">Converse com a DIRECT TI sobre o cenário atual, as restrições e o resultado esperado.</p></div><ButtonLink href="/contato" secondary>Falar com especialista</ButtonLink></Container></section>
  </>;
}
