import Link from "next/link";
import Image from "next/image";
import { ButtonLink, Container, SectionHeading } from "@/components/ui";
import { site } from "@/config/site";

const segments = ["Jurídico", "Frotas", "Logística", "Serviços", "Financeiro", "Energia", "Consultoria"];
const offerings = [
  ["◈", "Modernização de sistemas", "Transformamos sistemas legados em plataformas modernas, seguras e evolutivas.", "/servicos/modernizacao-de-sistemas"],
  ["◌", "Produtos SaaS", "Desenvolvemos soluções completas para gestão, dados e processos empresariais.", "/produtos"],
  ["⌘", "Integrações & APIs", "Conectamos sistemas, dados e pessoas para que sua operação funcione de forma inteligente.", "/servicos/integracoes-e-apis"],
] as const;
const products = site.products;
const services = ["Backend", "Frontend", "Power BI", "Integrações", "Arquitetura", "Cloud", "Banco de Dados", "Inteligência Artificial"];
const technologies = [".NET", "PHP", "Python", "React", "Next.js", "TypeScript", "Node.js", "NestJS", "Prisma", "SQL Server", "PostgreSQL", "Oracle", "Docker", "Redis", "GitHub", "Azure", "AWS", "Power BI"];
const cases = ["Sistema Jurídico Corporativo", "Modernização ASP Classic", "Dashboards Executivos", "Integrações REST", "Plataformas SaaS"];

function DashboardMockup() {
  return <div className="dashboard-shell" aria-label="Mockup ilustrativo do dashboard DirectOS">
    <div className="dashboard-sidebar"><div className="mini-brand"><span>◈</span> DirectOS</div>{["Dashboard", "Clientes", "Frotas", "Contratos", "Financeiro", "Relatórios", "Integrações"].map((item, i) => <div className={i === 0 ? "side-item active" : "side-item"} key={item}>◫ <span>{item}</span></div>)}</div>
    <div className="dashboard-main"><div className="dashboard-top"><b>Dashboard</b><span>◌ &nbsp; ◉</span></div><div className="metric-row">{[["Receita (mês)", "R$ 248.750", "+12,5%"], ["Contratos ativos", "1.482", "+0,2%"], ["Veículos ativos", "2.856", "+8,7%"], ["Tickets abertos", "23", "-14,3%"]].map(m => <div className="mini-metric" key={m[0]}><small>{m[0]}</small><strong>{m[1]}</strong><em>{m[2]}</em></div>)}</div><div className="chart-row"><div className="chart-card"><small>Receita mensal</small><div className="chart-line" /><div className="chart-months">Jan &nbsp; Mar &nbsp; Mai &nbsp; Jul &nbsp; Set &nbsp; Nov</div></div><div className="donut-card"><small>Distribuição</small><div className="donut"><b>2.856</b><span>TOTAL</span></div></div></div><div className="dashboard-footer">{["API", "Módulos", "Banco", "Cloud"].map((x, i) => <div key={x}><span>{["⌘", "▣", "▤", "⌁"][i]}</span><small>{x}</small><b>{["24", "08", "12", "99,9%"][i]}</b></div>)}</div></div>
  </div>;
}

export default function Home() {
  return <div className="home-page">
    <section className="hero-section"><div className="circuit-bg" /><Container className="hero-grid"><div className="hero-copy"><span className="hero-badge">SOFTWARE ENGINEERING · DATA · AI</span><h1>Projetamos, <span>modernizamos</span> e evoluímos plataformas digitais.</h1><p>Construímos software sob medida, modernizamos sistemas legados e desenvolvemos produtos SaaS que geram resultado real para o seu negócio.</p><div className="hero-actions"><ButtonLink href="/contato">Conheça nossos serviços</ButtonLink><ButtonLink href="/produtos" secondary>Ver produtos</ButtonLink></div><div className="metric-strip">{[["20+", "Anos de experiência"], ["5+", "Produtos desenvolvidos"], ["100%", "Atendimento remoto"], ["Multi-stack", "Tecnologias modernas"]].map(x => <div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></div><DashboardMockup /></Container></section>
    <section className="segment-section"><Container><p className="center-kicker">Atendemos <span>diversos segmentos</span></p><div className="segment-grid">{segments.map((x, i) => <div key={x}><span>{["♎", "▣", "◈", "▱", "ⓢ", "ϟ", "♧"][i]}</span>{x}</div>)}</div></Container></section>
    <section className="dark-section"><Container><SectionHeading eyebrow="O que fazemos" title="Tecnologia que resolve problemas reais." text="Da estratégia à evolução contínua, criamos soluções que conectam pessoas, processos e dados." center /><div className="offering-grid">{offerings.map(x => <Link href={x[3]} className="offering-card" key={x[1]}><span className="offering-icon">{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><span className="text-link">Saiba mais ↗</span></Link>)}</div></Container></section>
    <section className="dark-section products-section"><Container><SectionHeading eyebrow="Produtos" title="Produtos digitais em operação." center /><div className="product-grid">{products.map((product) => <a href={product.href} target="_blank" rel="noopener noreferrer" className="product-card product-card-preview" key={product.name}><div className="product-art"><Image src={product.image} alt={`Dashboard do ${product.name}`} fill sizes="(max-width: 600px) calc(100vw - 2.5rem), (max-width: 900px) calc(50vw - 3rem), 25vw" className="object-contain" /></div><h3>{product.name}</h3><p>{product.description}</p><small>{product.technologies.slice(0, 3).join(" · ")}</small><span className="text-link">Acessar produto ↗</span></a>)}</div></Container></section>
    <section className="dark-section services-section"><Container><SectionHeading eyebrow="Serviços" title="Uma equipe para cada camada do seu produto." center /><div className="service-grid">{services.map((x, i) => <div className="service-tile" key={x}><span>{["⌘", "▥", "▥", "⌁", "◇", "☁", "▤", "✦"][i]}</span><h3>{x}</h3><p>Especialistas para construir soluções confiáveis.</p></div>)}</div></Container></section>
    <section className="dark-section process-section"><Container><SectionHeading eyebrow="Processo" title="Como trabalhamos" center /><div className="process-line">{["Diagnóstico", "Arquitetura", "Desenvolvimento", "Entrega", "Evolução"].map((x, i) => <div key={x}><b>{String(i + 1).padStart(2, "0")}</b><h3>{x}</h3><p>{["Entendemos seu desafio.", "Projetamos a melhor solução.", "Construímos com qualidade.", "Implantamos, treinamos e acompanhamos.", "Evoluímos continuamente."][i]}</p></div>)}</div></Container></section>
    <section className="dark-section tech-section"><Container><SectionHeading eyebrow="Tecnologias" title="A base técnica que sustenta nossas entregas." center /><div className="tech-grid">{technologies.map(x => <span key={x}>{x}</span>)}</div></Container></section>
    <section className="dark-section cases-section"><Container><SectionHeading eyebrow="Cases" title="Experiência aplicada em cenários complexos." center /><div className="case-grid">{cases.map((x, i) => <Link href="/cases" className="case-card" key={x}><span>0{i + 1}</span><h3>{x}</h3><p>Conheça o cenário, os desafios e a abordagem técnica.</p><b>Ver case ↗</b></Link>)}</div></Container></section>
    <section className="dark-section story-section"><Container><SectionHeading eyebrow="Nossa história" title="Uma trajetória de evolução contínua." center /><div className="story-line">{["2001", "PUC-Rio", "EuroIT", "EasyCarros", "Petrobras", "DIRECT TI", "Produtos SaaS"].map((x, i) => <div key={x}><b>{i + 1}</b><strong>{x}</strong><span>{i === 0 ? "Início da jornada" : "Experiência que transforma"}</span></div>)}</div></Container></section>
    <section className="final-cta"><Container><div><p className="eyebrow">Vamos construir juntos</p><h2>O próximo sistema da sua empresa começa aqui.</h2></div><div className="cta-actions"><ButtonLink href="/contato">Conversar com especialista</ButtonLink><ButtonLink href="/produtos" secondary>Conhecer produtos</ButtonLink></div></Container></section>
  </div>;
}
