export type ProductStatus = "Em operação" | "Projeto demonstrativo";
export type Product = { name: string; category: string; description: string; highlights: readonly string[]; technologies: readonly string[]; status: ProductStatus; href: string; image: string; notes?: readonly string[] };
export const site = {
  name: "DIRECT TI", legalName: "DIRECT TI", description: "Consultoria e desenvolvimento de software para modernização de sistemas, integrações, dados e automação empresarial.", domain: "https://directti.dev.br", email: "direct.ti.tec@gmail.com", phone: "+55 (41) 99911-3960", whatsapp: "5541999113960", linkedin: "https://www.linkedin.com/in/sebastiao-oliveira-tech/", github: "https://github.com/tiaorj/",
  products: [
    { name: "DirectOS", category: "Gestão operacional SaaS", status: "Em operação", href: "https://directos.directti.dev.br/", image: "/products/directos-dashboard.webp", description: "Plataforma SaaS multiempresa para gestão de ordens de serviço, clientes, serviços, recebimentos, indicadores e comunicação operacional.", highlights: ["Ordens e serviços", "Indicadores operacionais", "Comunicação com clientes"], technologies: ["PHP", "SQL Server", "PDO SQLSRV", "Bootstrap", "JavaScript", "jQuery", "HTML", "CSS"], notes: ["Arquitetura multiempresa/SaaS, autenticação e sessões, proteção CSRF."] },
    { name: "Controle Financeiro", category: "Organização financeira", status: "Em operação", href: "https://financeiro.directti.dev.br/", image: "/products/financeiro-dashboard.webp", description: "Aplicação web para organização de receitas, despesas, categorias, carteiras e períodos financeiros.", highlights: ["Receitas e despesas", "Visão por carteira", "Categorias e períodos"], technologies: ["Python", "Flask", "SQL Server", "HTML", "CSS", "JavaScript", "Bootstrap"], notes: ["Inclui autenticação."] },
    { name: "Meu Álbum 26", category: "Gestão de coleções", status: "Projeto demonstrativo", href: "https://album.directti.dev.br/", image: "/products/album-dashboard.webp", description: "Aplicação web para controle de coleções, itens repetidos e faltantes, com autenticação, busca, filtros e compartilhamento.", highlights: ["Coleções e itens", "Filtros inteligentes", "Compartilhamento"], technologies: ["Next.js", "React", "TypeScript", "Supabase", "PostgreSQL", "Tailwind CSS"] },
  ] satisfies readonly Product[],
} as const;
export const navItems = [{ label: "Início", href: "/" }, { label: "Serviços", href: "/servicos" }, { label: "Legado360", href: "/legado360" }, { label: "Produtos", href: "/produtos" }, { label: "Cases", href: "/cases" }, { label: "Sobre", href: "/sobre" }, { label: "Contato", href: "/contato" }];
export const contactLinks = { whatsapp: (message = "Olá, gostaria de conversar sobre um projeto.") => `https://wa.me/${site.whatsapp}?text=${encodeURIComponent(message)}`, email: (subject = "Contato pelo site DIRECT TI") => `mailto:${site.email}?subject=${encodeURIComponent(subject)}` };
