import Link from "next/link";
import { site } from "@/config/site";

export function Container({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`mx-auto w-full max-w-7xl px-5 sm:px-8 ${className}`}>{children}</div>; }
export function SectionHeading({ eyebrow, title, text, center = false }: { eyebrow?: string; title: string; text?: string; center?: boolean }) { return <div className={`max-w-3xl ${center ? "mx-auto text-center" : ""}`}><p className="eyebrow">{eyebrow}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">{title}</h2>{text && <p className="mt-4 text-lg leading-8 text-slate-600">{text}</p>}</div>; }
export function ButtonLink({ href, children, secondary = false }: { href: string; children: React.ReactNode; secondary?: boolean }) { return <Link className={secondary ? "btn btn-secondary" : "btn btn-primary"} href={href}>{children}<span aria-hidden="true">→</span></Link>; }
export function ServiceCard({ title, text, href }: { title: string; text: string; href: string }) { return <article className="card group"><h3 className="text-xl font-semibold text-slate-950">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p><Link className="mt-5 inline-flex font-semibold text-blue-700 transition group-hover:text-blue-900" href={href}>Conhecer serviço <span className="ml-2">→</span></Link></article>; }
export function ProductCard({ product }: { product: (typeof site.products)[number] }) { return <article className="card flex flex-col"><div className="flex items-start justify-between gap-3"><h3 className="text-xl font-semibold text-slate-950">{product.name}</h3><span className="tag">{product.status}</span></div><p className="mt-3 flex-1 leading-7 text-slate-600">{product.description}</p><p className="mt-5 text-sm font-medium text-slate-500">{product.technologies.join(" · ")}</p><Link href={product.href} className="mt-5 inline-flex font-semibold text-blue-700">Ver produto <span className="ml-2">→</span></Link></article>; }
export function CTA() { return <section className="bg-slate-950 py-16 sm:py-20"><Container className="flex flex-col gap-7 md:flex-row md:items-end md:justify-between"><div className="max-w-2xl"><p className="eyebrow text-blue-300">Próximo passo</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Seu sistema precisa evoluir sem colocar a operação em risco?</h2><p className="mt-4 text-lg leading-8 text-slate-300">Converse com nossa equipe para avaliar o cenário atual, os principais riscos e os próximos passos.</p></div><div className="flex flex-wrap gap-3"><ButtonLink href={`https://wa.me/${site.whatsapp}`}>Falar pelo WhatsApp</ButtonLink><ButtonLink href="/contato" secondary>Enviar uma mensagem</ButtonLink></div></Container></section>; }
