import type { Metadata } from "next";
import { Container, CTA } from "@/components/ui";
import { PageHero } from "@/components/content";

export const metadata: Metadata = { title: "Cases", description: "Experiências da DIRECT TI em sistemas corporativos, modernização, dados e integrações." };

const cases = [
  { title: "Sistema jurídico corporativo", context: "Operação com regras processuais, documentos e etapas sensíveis.", problem: "Informações e regras estavam distribuídas entre fluxos que precisavam evoluir sem comprometer rotinas existentes.", challenge: "Organizar a evolução com rastreabilidade, preservando comportamentos essenciais e reduzindo dependências implícitas.", technologies: [".NET", "SQL Server", "APIs"], result: "Base mais clara para continuidade, manutenção e evolução incremental." },
  { title: "Plataforma de gestão de frotas", context: "Operação de mobilidade com registros, status e informações distribuídas.", problem: "A equipe precisava consolidar processos operacionais e melhorar a visibilidade sobre os dados de campo.", challenge: "Construir uma experiência consistente sem perder aderência às regras e exceções da operação.", technologies: ["ASP.NET", "JavaScript", "SQL Server"], result: "Maior visibilidade das atividades e organização dos fluxos de gestão." },
  { title: "Dashboard executivo e inteligência de dados", context: "Ambiente corporativo com dados em fontes distintas e leituras manuais.", problem: "Indicadores eram produzidos de formas diferentes, dificultando comparação e tomada de decisão.", challenge: "Definir modelo, métricas e contexto para transformar fontes heterogêneas em informação confiável.", technologies: ["Power BI", "DAX", "Power Query", "Oracle"], result: "Indicadores acessíveis, consistentes e adequados ao acompanhamento contínuo." },
  { title: "Modernização de ERP legado", context: "Aplicação essencial com dependências históricas e conhecimento concentrado.", problem: "A evolução era limitada pelo risco de alterar regras críticas e pela ausência de uma visão consolidada da arquitetura.", challenge: "Criar um caminho de modernização sem paralisar a operação nem exigir uma reescrita imediata.", technologies: ["ASP Classic", ".NET", "SQL Server"], result: "Roadmap priorizado para reduzir risco e orientar a substituição gradual de componentes." },
  { title: "Integração entre aplicações e serviços externos", context: "Sistemas corporativos que precisavam trocar informações com consistência.", problem: "Falhas de comunicação geravam retrabalho e correções manuais sem rastreabilidade suficiente.", challenge: "Definir contratos, autenticação, tratamento de exceções e reprocessamento para os fluxos críticos.", technologies: ["REST", "SOAP", "JSON", "XML"], result: "Comunicação mais previsível, observável e sustentável entre as aplicações." },
];

export default function Cases() { return <><PageHero eyebrow="Cases" title="Experiência aplicada a cenários corporativos" text="Os cases abaixo representam tipos de projetos e experiências da equipe. Por confidencialidade, não divulgamos nomes de clientes ou informações que permitam sua identificação."/><section className="py-16 sm:py-24"><Container><div className="grid gap-6">{cases.map((item, index) => <article className="card overflow-hidden p-0" key={item.title}><div className="border-b border-slate-200 bg-slate-50 px-6 py-5 sm:px-8"><div className="flex flex-wrap items-center justify-between gap-3"><span className="text-sm font-bold text-blue-700">CASE 0{index + 1}</span><span className="text-sm text-slate-500">{item.context}</span></div><h2 className="mt-3 text-2xl font-semibold text-slate-950">{item.title}</h2></div><div className="grid gap-6 px-6 py-6 sm:px-8 lg:grid-cols-2"><div className="grid gap-5 sm:grid-cols-2 lg:col-span-2"><div><p className="text-xs font-bold uppercase tracking-wide text-blue-700">Problema</p><p className="mt-2 leading-7 text-slate-600">{item.problem}</p></div><div><p className="text-xs font-bold uppercase tracking-wide text-blue-700">Desafio</p><p className="mt-2 leading-7 text-slate-600">{item.challenge}</p></div></div><div><p className="text-xs font-bold uppercase tracking-wide text-blue-700">Tecnologias</p><div className="mt-3 flex flex-wrap gap-2">{item.technologies.map((technology) => <span className="product-tech" key={technology}>{technology}</span>)}</div></div><div className="border-l-2 border-blue-600 pl-4"><p className="text-xs font-bold uppercase tracking-wide text-blue-700">Resultado</p><p className="mt-2 leading-7 text-slate-700">{item.result}</p></div></div></article>)}</div></Container></section><CTA/></>; }
